class ModNotFoundException < Exception; end
class InvalidModuleNameException < Exception; end
class PuppetfileNotFoundException < Exception; end
class InvalidPuppetfileException < Exception; end
class InvalidMetadataSource < Exception; end
class NoUnreleasedLine < Exception; end
class NoChangeLogFile < Exception; end
class UpstreamSourceMatch < Exception; end
class GitError < Exception; end
class RepoNotFound < Exception; end
class InvalidModule < Exception; end
class InvalidToken < Exception; end
class RemoteNotFound < Exception; end
class InvalidSshkey < Exception; end
class InvalidBranchName < Exception; end
class PatchError < Exception; end
class AlreadyReleased < Exception; end
class AlreadyDeployed < Exception; end
class TagExists < Exception; end