class ModNotFoundException < Exception; end
class InvalidModuleNameException < Exception; end
class PuppetfileNotFoundException < Exception; end
class InvalidPuppetfileException < Exception; end
class InvalidMetadataSource < Exception; end
class NoUnreleasedLine < Exception; end
class NoChangeLogFile < Exception; end
class UpstreamSourceMatch < Exception; end
class GitError < Exception; end